import { useState } from "react";
import { motion } from "framer-motion";
import { FileText, Download, Eye, TestTube } from "lucide-react";
const API = import.meta.env.VITE_API_URL || "http://localhost:3001";

const TestClinicalReport = () => {
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);

  const generateTestReport = async () => {
    try {
      setLoading(true);
      setError(null);
      
      console.log('🧪 Generating test clinical report...');
      
      const response = await fetch('http://localhost:3001/api/clinical-reports/test', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' }
      });
      
      const data = await response.json();
      
      if (data.success) {
        setReport(data.report);
        console.log('✅ Test report generated:', data.report);
      } else {
        setError('Failed to generate test report');
      }
    } catch (error) {
      console.error('Error generating test report:', error);
      setError('Error generating test report');
    } finally {
      setLoading(false);
    }
  };

  const downloadReport = async () => {
    if (!report) return;
    
    try {
      // Generate PDF content
      const pdfContent = `
CLINICAL ASSESSMENT REPORT

Patient: ${report.patientName}
Assessment: ${report.assessmentType.toUpperCase()} ${report.assessmentType === 'phq9' ? 'Depression Screening' : 'Anxiety Assessment'}
Date: ${new Date(report.completedAt).toLocaleDateString()}

RESULTS
Score: ${report.totalScore} / ${report.maxScore}
Severity Level: ${report.severityLevel}
Risk Level: ${report.riskLevel.toUpperCase()}

QUESTION BREAKDOWN
${report.questionBreakdown.map((q: any) => 
  `Q${q.questionId} – ${q.questionText}
  Answer: ${q.userAnswer}
  Score: ${q.score}/3`
).join('\n\n')}

RISK INDICATORS
${report.riskIndicators.length > 0 ? 
  report.riskIndicators.map((indicator: string) => `• ${indicator}`).join('\n') : 
  '• No significant risk indicators identified'
}

CONVERSATION SUMMARY
${report.conversationSummary}

RECOMMENDED ACTION
${report.recommendedAction}

---
Generated by NeuroScan AI Mental Health Triage Platform
      `.trim();
      
      const blob = new Blob([pdfContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `test-clinical-report-${Date.now()}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error downloading report:', error);
      alert('Error downloading report');
    }
  };

  return (
    <div className="min-h-screen bg-[#0a0b0f] text-white p-6">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-white mb-2">Clinical Report Testing</h1>
          <p className="text-gray-400">Test the clinical report generation system</p>
        </div>

        {/* Generate Test Report Button */}
        <div className="text-center mb-8">
          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={generateTestReport}
            disabled={loading}
            className="px-8 py-4 bg-gradient-to-r from-purple-500 to-indigo-600 text-white rounded-xl text-lg font-medium hover:from-purple-600 hover:to-indigo-700 transition-all duration-300 shadow-lg disabled:opacity-50 flex items-center gap-3 mx-auto"
          >
            <TestTube className="w-5 h-5" />
            {loading ? 'Generating...' : 'Generate Test Clinical Report'}
          </motion.button>
        </div>

        {/* Error Display */}
        {error && (
          <div className="bg-red-500/10 border border-red-500/30 rounded-xl p-4 mb-6">
            <p className="text-red-400">{error}</p>
          </div>
        )}

        {/* Report Display */}
        {report && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-xl p-6"
          >
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl font-semibold flex items-center gap-2">
                <FileText className="w-5 h-5 text-purple-400" />
                Clinical Report Generated
              </h2>
              <div className="flex gap-2">
                <button
                  onClick={downloadReport}
                  className="px-4 py-2 bg-green-500/20 text-green-400 rounded-lg hover:bg-green-500/30 transition-colors flex items-center gap-2"
                >
                  <Download className="w-4 h-4" />
                  Download
                </button>
              </div>
            </div>

            {/* Report Summary */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
              <div className="bg-black/30 rounded-lg p-4">
                <p className="text-gray-400 text-sm">Patient</p>
                <p className="text-white font-medium">{report.patientName}</p>
              </div>
              <div className="bg-black/30 rounded-lg p-4">
                <p className="text-gray-400 text-sm">Score</p>
                <p className="text-white font-medium">{report.totalScore}/{report.maxScore}</p>
              </div>
              <div className="bg-black/30 rounded-lg p-4">
                <p className="text-gray-400 text-sm">Severity</p>
                <p className={`font-medium ${
                  report.riskLevel === 'severe' ? 'text-red-400' :
                  report.riskLevel === 'moderate' ? 'text-orange-400' :
                  report.riskLevel === 'mild' ? 'text-yellow-400' : 'text-green-400'
                }`}>
                  {report.severityLevel}
                </p>
              </div>
            </div>

            {/* Question Breakdown */}
            <div className="mb-6">
              <h3 className="text-lg font-semibold mb-4">Question Breakdown</h3>
              <div className="space-y-3">
                {report.questionBreakdown.slice(0, 3).map((question: any) => (
                  <div key={question.questionId} className="bg-black/30 rounded-lg p-3">
                    <div className="flex justify-between items-start">
                      <div className="flex-1">
                        <p className="text-white text-sm font-medium mb-1">
                          Q{question.questionId}: {question.questionText.substring(0, 60)}...
                        </p>
                        <p className="text-gray-400 text-xs">
                          Answer: {question.userAnswer}
                        </p>
                      </div>
                      <div className="text-right ml-3">
                        <span className={`text-lg font-bold ${
                          question.score === 0 ? 'text-green-400' :
                          question.score === 1 ? 'text-yellow-400' :
                          question.score === 2 ? 'text-orange-400' : 'text-red-400'
                        }`}>
                          {question.score}/3
                        </span>
                      </div>
                    </div>
                  </div>
                ))}
                <p className="text-gray-400 text-sm text-center">
                  ... and {report.questionBreakdown.length - 3} more questions
                </p>
              </div>
            </div>

            {/* Risk Indicators */}
            <div className="mb-6">
              <h3 className="text-lg font-semibold mb-4">Risk Indicators</h3>
              <div className="space-y-2">
                {report.riskIndicators.map((indicator: string, index: number) => (
                  <div key={index} className="flex items-start gap-3">
                    <div className="w-2 h-2 bg-orange-400 rounded-full mt-2 flex-shrink-0" />
                    <p className="text-gray-300 text-sm">{indicator}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Recommended Action */}
            <div className="bg-blue-500/10 border border-blue-500/30 rounded-lg p-4">
              <h3 className="text-blue-400 font-medium mb-2">Recommended Action</h3>
              <p className="text-gray-300 text-sm">{report.recommendedAction}</p>
            </div>

            {/* JSON Data (for debugging) */}
            <details className="mt-6">
              <summary className="text-gray-400 cursor-pointer hover:text-white">
                View Raw JSON Data
              </summary>
              <pre className="mt-2 p-4 bg-black/50 rounded-lg text-xs text-gray-300 overflow-auto">
                {JSON.stringify(report, null, 2)}
              </pre>
            </details>
          </motion.div>
        )}

        {/* Instructions */}
        <div className="mt-8 bg-white/5 backdrop-blur-xl border border-white/10 rounded-xl p-6">
          <h3 className="text-lg font-semibold mb-4">Testing Instructions</h3>
          <div className="space-y-2 text-sm text-gray-300">
            <p>1. Click "Generate Test Clinical Report" to create a sample report with mock PHQ-9 data</p>
            <p>2. Review the generated report structure and content</p>
            <p>3. Test the download functionality</p>
            <p>4. Verify that all clinical elements are present: scoring, risk assessment, recommendations</p>
            <p>5. Check that the report follows medical documentation standards</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TestClinicalReport;
